import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pickle

# Dictionary containing diseases and associated symptoms
disease_symptoms = {'Abscess': ['redness', 'pain', 'swell'],
 'Acquired Capillary Haemangioma of Eyelid': ['raised red or bluelesion'],
 'Acquired Immuno Deficiency Syndrome': ['early'],
 'Acute encephalitis syndrome': ['headache',
  'fever',
  'confusion',
  'stiff neck',
  'vomit'],
 'Alcohol Abuse and Alcoholism': ['drinking large amounts of alcohol over a long period',
  'difficulty cutting down',
  'acquiring and drinking alcohol taking up a lot of time',
  'usage resulting in problems',
  'withdrawaloccurring when stopping'],
 'Alopecia (hair loss)': ['loss ofhairfrom part of the head or body.'],
 'Alzheimer': ['memory loss',
  'problems with language',
  'disorientation',
  'mood swings'],
 'Amaurosis Fugax': ['temporary fleeting of vision in one or both eyes'],
 'Amblyopia': ['decreased vision'],
 'Amoebiasis': ['bloody diarrhea', 'abdominal pain'],
 'Anaemia': ['feeling tired',
  'pale skin',
  'weakness',
  'shortness of breath',
  'feeling faint'],
 'Aniseikonia': ['objects different sizes in each eye'],
 'Anisometropia': ["eyes' refractive power differs significantly"],
 'Anthrax': ['skin form'],
 'Appendicitis': ['periumbilical or right lowerabdominal pain',
  'vomit',
  'decreased appetite'],
 'Arthritis': ['joint pain',
  'stiffness',
  'redness',
  'swell',
  'decreasedrange of motion'],
 'Asthma': ['recurring episodes ofwheezing',
  'cough',
  'chest tightness',
  'shortness of breath'],
 'Astigmatism': ['distorted orblurred visionat all distances',
  'eyestrain',
  'headache'],
 'Atrophy': ['loss of body cells', 'signs ofageing'],
 'Autism': ['difficulties insocial interaction',
  'verbal andnonverbal communication',
  'and the presence of repetitive behavior or restricted interests'],
 'Bad Breath (Halitosis)': ['unpleasantsmellpresent onbreath'],
 "Bell's Palsy": ['inability to move thefacial muscleson one side',
  'change intaste',
  'pain around the ear'],
 'Blindness': ['decreased ability tosee'],
 'Botulism': ['weakness',
  'trouble seeing',
  'feeling tired',
  'trouble speaking'],
 'Brain Tumour': ['vary depending on the part of the brain involved',
  'headache',
  'seizure',
  'problem withvision',
  'vomit',
  'mentalchanges'],
 'Bronchitis': ['coughingupmucus',
  'wheeze',
  'shortness of breath',
  'chest discomfort'],
 'Brucellosis': ['fever',
  'chill',
  'loss of appetite',
  'sweat',
  'weakness',
  'fatigue',
  'joint',
  'muscle and back pain',
  'headache'],
 'Bubonic plague': ['fever', 'headache', 'vomit', 'swollen lymph nodes'],
 'Bunion': ['prominent',
  'red',
  'and painful joint at the base of the big toe'],
 'Burns': ['first degree'],
 'Cancer': ['lump',
  'abnormal bleeding',
  'prolonged cough',
  'unexplainedweight loss',
  'change inbowel movements'],
 'Candidiasis': ['white patches or vaginal discharge', 'itch'],
 'Carbon monoxide poisoning': ['headache',
  'dizziness',
  'weakness',
  'vomit',
  'chest pain',
  'confusion'],
 'Carpal Tunnel Syndrome': ['numbness',
  'tinglingin the thumb',
  'index',
  'middle finger',
  'and half of ring finger.'],
 'Cavities': ['pain', 'tooth loss', 'difficulty eating'],
 'Celiacs disease': ['none ornon-specific',
  'abdominal distention',
  'diarrhoea',
  'constipation',
  'malabsorption',
  'weight loss',
  'dermatitis herpetiformis'],
 'Cerebral palsy': ['poor coordinationstifforloosemusclesweak musclestremors'],
 'Chagas disease': ['fever', 'large lymph nodes', 'headache'],
 'Chalazion': ['red', 'non painfulcystin middle of theeyelid'],
 'Chickenpox': ['small',
  'itchy blisters',
  'headache',
  'loss of appetite',
  'tiredness',
  'fever'],
 'Chikungunya Fever': ['fever', 'joint pain'],
 'Chlamydia': ['vaginal discharge',
  'discharge from the penis',
  'burning with urination'],
 'Cholera': ['large amounts of waterydiarrhea', 'vomit', 'muscle cramps'],
 'Chronic fatigue syndrome': ['worsening of symptoms with activity',
  'long-term fatigue',
  'sleep problems',
  'others'],
 'Chronic obstructive pulmonary disease (COPD)': ['shortness of breath',
  'chroniccough'],
 'Cleft Lip and Cleft Palate': ['opening in the upper lip that may extend into the nose orpalate'],
 'Colorectal Cancer': ['blood in stool',
  'change in bowel movements',
  'unintentionalweight loss',
  'vomit',
  'fatigue'],
 'Common cold': ['cough', 'sore throat', 'runny nose', 'fever'],
 'Congenital anomalies (birth defects)': ['physical disability',
  'intellectual disability',
  'developmental disability'],
 'Congestive heart disease': ['shortness of breath',
  'exhaustion',
  'swollen legs'],
 'Corneal Abrasion': ['eye pain', 'light sensitivity'],
 'Coronary Heart Disease': ['chest pain', 'shortness of breath'],
 'Coronavirus disease 2019 (COVID-19)': ['fever',
  'cough',
  'fatigue',
  'shortness of breath',
  'vomit',
  'loss of taste or smell; some cases asymptomatic'],
 'Crimean Congo haemorrhagic fever (CCHF)': ['fever',
  'muscle pains',
  'headache',
  'vomit',
  'diarrhea',
  'bleeding into the skin'],
 'Dehydration': ['increasedthirst',
  'tiredness',
  'decreased urine',
  'dizziness',
  'headache',
  'and confusion'],
 'Dementia': ['decreased ability tothinkand remember',
  'emotional problems',
  'problems withlanguage',
  'decreasedmotivation'],
 'Dengue': ['fever',
  'headache',
  'muscle and joint pain',
  'rash. can be severe',
  'mild or asymptomatic'],
 'Diabetes Mellitus': ['frequent urinationincreased thirstincreased hunger'],
 'Diabetic Retinopathy': ['often asymptomatic',
  'but can causespots in the eyeand vision loss.'],
 'Diarrhea': ['loose frequent bowel movements', 'dehydration'],
 'Diphtheria': ['sore throat', 'fever', 'barking cough'],
 "Down's Syndrome": ['delayeddevelopment',
  'characteristic physical features',
  'mild to moderateintellectual disability'],
 'Dracunculiasis (guinea-worm disease)': ['painful blister that a long white string-like worm slowly crawls out of'],
 'Dysentery': ['bloody diarrhea', 'abdominal pain', 'fever'],
 'Early pregnancy loss': ['vaginal bleedingwith or without pain'],
 'Ebola': ['fever',
  'sore throat',
  'muscular pain',
  'headache',
  'diarrhoea',
  'bleeding'],
 'Eclampsia': ['seizure', 'high blood pressure'],
 'Ectopic pregnancy': ['abdominal pain', 'vaginal bleeding'],
 'Eczema': ['itchiness', 'red skin', 'rash'],
 'Endometriosis': ['pelvic pain', 'infertility'],
 'Epilepsy': ['periods of loss of consciousness',
  'abnormal shaking',
  'star',
  'change in vision',
  'mood changes and/or other cognitive disturbances'],
 'Fibroids': ['painfulorheavy periods'],
 'Fibromyalgia': ['widespread pain', 'feeling tired', 'sleep problems'],
 'Frost Bite': ['numbness', 'feeling cold', 'clumsiness', 'pale color'],
 'Gaming disorder': ['problem gambling',
  'depression',
  'social withdrawal',
  'playingvideo gamesfor extremely long periods of time'],
 'Gangrene': ['change in skin color to red or black',
  'numbness',
  'pain',
  'skin breakdown',
  'coolness'],
 'Gastroenteritis': ['diarrhea', 'vomit', 'abdominalpain', 'fever'],
 'Genital herpes': ['small blistersthat break open to form painfululcers',
  'flu-like symptoms'],
 'GERD': ['taste of acid',
  'heartburn',
  'bad breath',
  'chest pain',
  'breathing problems'],
 'Glaucoma': ['.mw-parser-output .hlist dl',
  '.mw-parser-output .hlist ol',
  '.mw-parser-output .hlist ul{margin'],
 'Gonorrhea': ['burning with urination',
  'vaginal discharge',
  'discharge from thepenis',
  'pelvic pain',
  'testicular pain'],
 'Guillain-Barré syndrome': ['muscle weakness beginning in the feet and hands',
  'usually ascending'],
 'Haemophilia': ['easy and prolongedbleeding'],
 'Hand, Foot and Mouth Disease': ['fever',
  'flat discolored spots or bumpsthat may blister'],
 'Hepatitis A': ['nausea',
  'vomit',
  'diarrhea',
  'dark urine',
  'jaundice',
  'fever',
  'abdominal pain'],
 'Hepatitis B': ['yellowish skin',
  'tiredness',
  'dark urine',
  'abdominal pain'],
 'Hepatitis C': ['typically none'],
 'Hepatitis D': ['feeling tired', 'nausea and vomiting'],
 'Hepatitis E': ['nausea', 'jaundice'],
 'Hepatitis': ['yellowish skin', 'poor appetite', 'abdominal pain'],
 'Herpes Simplex': ['blisters that break open and form smallulcers',
  'fever',
  'swollenlymph nodes'],
 'Human papillomavirus': ['wart'],
 'Hypermetropia': ['near blur', 'distance and near blur', 'asthenopia'],
 'Hyperthyroidism': ['irritability',
  'muscle weakness',
  'sleeping problems',
  'fast heartbeat',
  'heat intolerance',
  'diarrhea',
  'enlargement of the thyroid',
  'weight loss'],
 'Hypothyroid': ['poor ability to tolerate cold',
  'feeling tired',
  'constipation',
  'weight gain',
  'depression',
  'anxiety',
  'irritability'],
 'Hypotonia': ['muscle weakness'],
 'Impetigo': ['yellowish skin crusts', 'painful'],
 'Influenza': ['fever',
  'runny nose',
  'sore throat',
  'muscle pain',
  'headache',
  'cough',
  'fatigue'],
 'Insomnia': ['troublesleeping',
  'daytime sleepiness',
  'low energy',
  'irritability',
  'depressed mood'],
 'Interstitial cystitis': ['chronic painof the bladder',
  'feeling the need to urinate right away',
  'needing to urinate often',
  'pain with sex'],
 'Iritis': ['headache',
  'red eyes',
  'blurred vision',
  'photophobia',
  'burning and redness of the eye'],
 'Iron Deficiency Anemia': ['feeling tired',
  'weakness',
  'shortness of breath',
  'confusion',
  'pallor'],
 'Irritable bowel syndrome': ['diarrhea', 'constipation', 'abdominalpain'],
 'Japanese Encephalitis': ['headache',
  'fever',
  'vomit',
  'confusion',
  'seizure'],
 'Jaundice': ['yellowishcoloration of skin andsclera', 'itchiness'],
 'Kaposi’s Sarcoma': ['purplecolored skin lesions'],
 'Keratoconjunctivitis Sicca (Dry eye syndrome)': ['dry eyes',
  'irritation',
  'redness',
  'discharge',
  'blurred vision'],
 'Keratoconus': ['blurry vision', 'nearsightedness', 'light sensitivity'],
 'Kuru': ['body tremors',
  'random outbursts of laughter',
  'gradual loss ofcoordination'],
 'lactose intolerance': ['abdominal pain',
  'bloating',
  'diarrhea',
  'flatulence',
  'nausea'],
 'Laryngitis': ['hoarse voice', 'fever', 'pain'],
 'Lead poisoning': ['intellectual disability',
  'abdominal pain',
  'constipation',
  'headache',
  'irritability',
  'memory problems',
  'inability to have children',
  'tinglingin the hands and feet'],
 'Legionellosis': ['cough',
  'shortness of breath',
  'fever',
  'muscle pains',
  'headache'],
 'Leprosy': ['decreased ability to feel pain'],
 'Leptospirosis': ['headache', 'muscle pains', 'fever'],
 'Leukemia': ['bleeding',
  'bruising',
  'fatigue',
  'fever',
  'increased risk of infections'],
 'Lung cancer': ['cough', 'shortness of breath', 'chest pain'],
 'Lupus erythematosus': ['painful and swollen joints',
  'fever',
  'chest pain',
  'hair loss',
  'mouth ulcers',
  'swollen lymph nodes',
  'feeling tired',
  'redrash'],
 'Lyme disease': ['expanding area of redness at the site of atickbite',
  'fever',
  'headache',
  'tiredness'],
 'Lymphoma': ['enlarged lymph nodes',
  'fever',
  'sweat',
  'unintended weight loss',
  'itch',
  'feeling tired'],
 'Mad cow disease': ['abnormal behavior',
  'trouble walking',
  'weight loss',
  'inability to move'],
 'Malaria': ['fever', 'vomit', 'headache', 'yellow skin'],
 'Marburg fever': ['fever', 'weakness', 'muscle pain'],
 'Mastitis': ['localized breast pain and redness', 'fever'],
 'Measles': ['fever', 'cough', 'runny nose', 'inflamed eyes', 'rash'],
 'Melanoma': ['molethat is increasing in size',
  'has irregular edges',
  'change in color',
  'itchiness',
  'orskin breakdown.'],
 'Middle East respiratory syndrome coronavirus (MERS‐CoV)': ['fever',
  'cough',
  'shortness of breath'],
 'Migraine': ['headache',
  'nausea',
  'sensitivity to light',
  'sound',
  'andsmell'],
 'Mononucleosis': ['fever',
  'sore throat',
  'enlarged lymph nodesin the neck',
  'fatigue'],
 'Mouth Breathing': ['snore',
  'dry mouth',
  'hoarse voice',
  'bad breath',
  'fatigue',
  'sleep apnea'],
 'Multiple myeloma': ['bone pain', 'fatigue'],
 'Multiple sclerosis': ['variable',
  'including almost any neurological symptom or sign',
  'withautonomic',
  'visual',
  'motor',
  'and sensory problems being the most common.'],
 'Mumps': ['parotitis and non-specific symptoms such as fever',
  'headache',
  'malaise',
  'muscle pain',
  'and loss of appetite'],
 'Muscular dystrophy': ['increasing weakening',
  'breakdown ofskeletal muscles',
  'trouble walking'],
 'Myasthenia gravis': ['varying degreesmuscle weakness',
  'double vision',
  'drooping eyelids',
  'trouble talking',
  'trouble walking'],
 'Myocardial Infarction (Heart Attack)': ['chest pain',
  'shortness of breath',
  'nausea/vomiting',
  'dizzinessorlightheadedness',
  'cold sweat',
  'feeling tired; arm',
  'neck',
  'back',
  'jaw',
  'or stomach pain',
  'decreased levelortotal loss of consciousness'],
 'Myopia': ['distant objects appearblurry',
  'close objects appear normal',
  'headache',
  'eye strain'],
 'Narcolepsy': ['excessive daytime sleepiness',
  'involuntary sleep episodes',
  'sudden loss of muscle strength',
  'hallucination'],
 'Nasal Polyps': ['trouble breathing through the nose',
  'loss of smell',
  'decreased taste',
  'post nasal drip',
  'runny nose'],
 'Nausea and Vomiting of Pregnancy and  Hyperemesis gravidarum': ['nauseaandvomitingsuch thatweight lossanddehydrationoccur'],
 'Necrotizing Fasciitis': ['severe pain',
  'fever',
  'purple colored skin in the affected area'],
 'Neoplasm': ['lump'],
 'Obesity': ['increased fat'],
 'Obsessive Compulsive Disorder': ['feel the need to check things repeatedly',
  'performcertain routines repeatedly',
  'havecertain thoughts repeatedly'],
 'Oral Cancer': ['persistent rough white or red patch in the mouth lasting longer than  weeks',
  'ulceration',
  'lumps/bumps in the neck',
  'pain',
  'loose teeth',
  'difficulty swallowing'],
 'Osteoarthritis': ['joint pain',
  'stiffness',
  'joint swelling',
  'decreasedrange of motion'],
 'Osteomyelitis': ['pain in a specific bone',
  'overlying redness',
  'fever',
  'weakness'],
 'Osteoporosis': ['increased risk of abroken bone'],
 'Paratyphoid fever': ['fever', 'headache', 'rash', 'weakness'],
 "Parkinson's Disease": ['rigidity',
  'slowness of movement',
  'tremor',
  'difficulty walking'],
 'Pelvic inflammatory disease': ['lower abdominal pain',
  'vaginal discharge',
  'fever',
  'burning with urination',
  'pain with sex',
  'irregular menstruation'],
 'Pericarditis': ['sharpchest pain',
  'better sitting up and worse with lying down',
  'fever'],
 'Peritonitis': ['severe pain', 'swelling of the abdomen', 'fever'],
 'Pneumonia': ['cough', 'shortness of breath', 'chest pain', 'fever'],
 'Poliomyelitis': ['fever', 'sore throat'],
 'Polycystic ovary syndrome (PCOS)': ['irregularmenstrual periods',
  'heavy periods',
  'excess hair',
  'acne',
  'pelvic pain',
  'difficulty getting pregnant',
  'patches of thick',
  'darker',
  'velvety skin'],
 'Porphyria': ['depending on subtype—abdominal pain',
  'chest pain',
  'vomit',
  'confusion',
  'constipation',
  'fever',
  'seizure',
  'blisterswith sunlight'],
 'Post-herpetic neuralgia': ['burning or stabbing pain',
  "pain doesn't end after theshinglessubsides."],
 'Preeclampsia': ['high blood pressure', 'protein in the urine'],
 'Premenstrual syndrome': ['fatigue',
  'irritabilityand other mood changes',
  'tender breasts',
  'abdominal bloating'],
 'Presbyopia': ['difficulty reading small print',
  'having to hold reading material farther away',
  'headache',
  'eyestrain'],
 'Preterm birth': ["birthof ababyat younger than  weeks'gestational age"],
 'Progeria': ['growth delay', 'short height', 'small face', 'hair loss'],
 'Psoriasis': ['red', 'itchy', 'scaly patches of skin'],
 'Puerperal sepsis': ['fever',
  'lower abdominal pain',
  'bad-smelling vaginal discharge'],
 'Pulmonary embolism': ['shortness of breath',
  'chest pain',
  'coughing up blood'],
 'Quinsy': ['fever',
  'throat pain',
  'trouble opening the mouth',
  'change to the voice'],
 'Rabies': ['fever',
  'extreme aversion to water',
  'confusion',
  'excessive salivary secretion',
  'hallucination',
  'disrupted sleep',
  'paralysis',
  'coma',
  'hyperactivity',
  'headache',
  'nausea',
  'vomit',
  'anxiety'],
 "Raynaud's Phenomenon": ['an affected part turningwhite',
  'thenblue',
  'then red',
  'burning'],
 'Repetitive strain injury': ['sore wrists',
  'ache',
  'pulsing pain',
  'tingle',
  'extremity weakness'],
 'Rheumatic fever': ['fever',
  'multiplepainful joints',
  'involuntary muscle movements',
  'erythema marginatum'],
 'Rickets': ['bowed legs',
  'stunted growth',
  'bone pain',
  'large forehead',
  'trouble sleeping'],
 'Rift Valley fever': ['fever', 'muscle pains', 'headache'],
 'Rocky Mountain spotted fever': ['early'],
 'Rubella': ['rash',
  'swollen lymph nodes',
  'fever',
  'sore throat',
  'feeling tired'],
 'Sarcoidosis': ['depends on the organ involvedlungs'],
 'SARS': ['fever',
  'persistent dry cough',
  'headache',
  'muscle pains',
  'difficulty breathing'],
 'Scabies': ['itchiness', 'pimple-like rash'],
 'Scarlet fever': ['sore throat',
  'fever',
  'headache',
  'swollenlymph nodes in the neck',
  'characteristic rash'],
 'Schizophrenia': ['hallucination',
  'delusion',
  'confused thought and behavior',
  'inappropriate affect'],
 'Sciatica': ['paingoing down the leg from thelower back',
  'weakness or numbness of the affected leg'],
 'Scurvy': ['weakness',
  'feeling tired',
  'changes to hair',
  'sore arms and legs',
  'gum disease',
  'easy bleeding'],
 'Sexually transmitted infections (STIs)': ['vaginal discharge',
  'penile discharge',
  'ulcers on or around the genitals',
  'pelvic pain'],
 'Shaken Baby Syndrome': ['variable'],
 'Shigellosis': ['diarrhea', 'fever', 'abdominal pain'],
 'Shin splints': ['pain along the inside edge of the shinbone'],
 'Shingles': ['painful rash'],
 'Sickle-cell anemia': ['attacks of pain',
  'anemia',
  'swelling in the hands and feet',
  'bacterial infections',
  'stroke'],
 'Stevens-Johnson syndrome': ['fever',
  'skin blisters',
  'skin peeling',
  'painful skin',
  'red eyes'],
 'Stomach ulcers': ['heartburn',
  'upper abdominal pain',
  'nausea',
  'belching',
  'vomit',
  'blood in the stool',
  'weight loss',
  'weight gain',
  'bloating',
  'loss of appetite',
  'yellowing of the skin and whites of the eyes',
  'difficulty swallowing'],
 'Strep throat': ['fever', 'sore throat', 'enlarged lymph nodes'],
 'Stroke': ['inability to move or feelon one side of the body',
  'problems understandingorspeaking',
  'dizziness',
  'loss of vision to one side'],
 'Sub-conjunctival Haemorrhage': ['red spot over whites of the eye',
  'little to no pain'],
 'Syphilis': ['firm', 'painless', 'non-itchyskin ulcer'],
 'Taeniasis': ['weight loss', 'abdominal pain'],
 'Tay-Sachs disease': ['initially'],
 'Tennis elbow': ['painful and tender outer part of the elbow'],
 'Tetanus': ['fever',
  'cramped-up jaw',
  'muscle spasms',
  'headache',
  'seizure',
  'sweat',
  'and trouble swallowing'],
 'Thalassaemia': ['feelingtired',
  'pale skin',
  'enlarged spleen',
  'yellowish skin',
  'dark urine'],
 'Tinnitus': ['hearing sound when no external sound is present'],
 'Tonsillitis': ['sore throat',
  'fever',
  'enlargement of the tonsils',
  'trouble swallowing',
  'large lymph nodesaround the neck'],
 'Toxic shock syndrome': ['fever',
  'rash',
  'skin peeling',
  'low blood pressure'],
 'Trachoma': ['eye pain', 'blindness'],
 'Trichinosis': ['initially'],
 'Trichomoniasis': ['itching in thegenital area',
  'bad smelling thinvaginal discharge',
  'burning with urination',
  'pain with sex'],
 'Tuberculosis': ['chronic cough',
  'fever',
  'cough with bloody mucus',
  'weight loss'],
 'Tularemia': ['fever', 'skin ulcer', 'large lymph nodes'],
 'Turners Syndrome': ['webbed neck', 'short stature', 'heart defects'],
 'Urticaria': ['red', 'raise', 'itchy bumps'],
 'Varicose Veins': ['fullness', 'pain in the area'],
 'Vasovagal syncope': ['loss of consciousnessbefore which there may be sweating',
  'decreased ability to see',
  'ringing in the ears'],
 'Vitamin B12 Deficiency': ['decreased ability to think',
  'feeling tired',
  'depression',
  'irritability',
  'abnormal sensations',
  'changes in reflexes'],
 'Vitiligo': ['patches ofwhite skin'],
 'Warts': ['skin growth usually occurring on the hands',
  'foot',
  'or genitals'],
 'Yaws': ['hard swelling of the skin', 'ulcer', 'joint and bone pain'],
 'Yellow Fever': ['fever', 'chill', 'muscle pain', 'headache', 'yellow skin']}


# Transform dictionary into a list of lists format for Apriori algorithm
transactions = list(disease_symptoms.values())

# Convert symptom lists to sets for faster membership testing
transactions = [set(symptoms) for symptoms in transactions]

# Convert transactions to a DataFrame
df = pd.DataFrame(transactions)

# Convert sets back to lists for Apriori algorithm
transactions = [list(symptoms) for symptoms in transactions]

# Apply one-hot encoding
df = pd.get_dummies(df.apply(pd.Series).stack()).groupby(level=0).sum()

# Convert transactions back to lists for Apriori algorithm
frequent_itemsets = apriori(df, min_support=0.005, use_colnames=True)

# Print frequent itemsets
print("Frequent Itemsets:")
print(frequent_itemsets)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)
print("\nAssociation Rules:")
print(rules)

with open('./Dataset/association_rules.pkl', 'wb') as f:
    pickle.dump(rules, f)